Soporte para Twitch
SeaOfThievesES/Tabernera pull request #12
Opened 2018-07-31 09:47 UTC by StartForKillerMC

Esta parte del proyecto completa la tarjeta https://trello.com/c/EIsYtwj8/21-twitch.

**<------------------------------------------------------------------------------------------------------------>**
Añade cuatro funciones que se engloban en dos archivos:
-En el **archivo principal**, detecta los canales que están en directo y lo manda a un canal de texto de Discord.
-En el **segundo** archivo se incluyen los comandos, tanto como para añadir quitar como listar usuarios. Tanto de Twitch como de Discord.
**<------------------------------------------------------------------------------------------------------------>**

Se ha probado con un stream y con dos, intentando saltar el bloqueo del juego.

**Nota**: El archivo que se encarga de comprobar las retransmisiones esta con un max-depth 6 para evitar mal uso de recursos.

2018-07-31 11:24 UTC, kyranet submitted a review, later dismissed
Realmente no necesitabas cambiar la regla max-depth de ESLint, solamente necesitabas aprender a refactorizar tu código.

2018-07-31 11:24 UTC, kyranet commented on src/commands/Utiles/twitch.js
> +	async quitar(msg, [usuario, ...nombreCuentaTwitch]) {
`nombreCuentaTwitch` no es un array

2018-07-31 11:24 UTC, kyranet commented on src/commands/Utiles/twitch.js
> +		await r.table('streamers').get(usuario.id).delete();
```js
const nombre = r.table('streamers').get(usuario.id)('nombreCuentaTwitch').default(null);
if (!nombre) throw `No existe en la base de datos`;

await r.table('streamers').get(usuario.id).delete();
return msg.send('...');
```

2018-07-31 11:24 UTC, kyranet commented on src/commands/Utiles/twitch.js
> +		for (let i = 0; i < tabla.length; i++) {
```js
const cuentas = [], usuarios = [];
let i = 1;
for (const entrada of tabla) {
	cuentas.push(`${i++}. ${entrada.nombreCuentaTwitch}`);
	usuarios.push(await msg.guild.members.get(entrada.id)
		.then(member => member.displayName)
		.catch(() => entrada.id));
}

return msg.sendEmbed(new MessageEmbed()
	.setTitle('<:twitch:473533904457039872> Lista de streamers')
	.setColor(8478656)
	.addField('Cuenta:', cuentas.join('\n'), true)
	.addField('Usuario:', usuarios.join('\n'), true));

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +	constructor(...args) {
useless-constructor (el valor de name es, por defecto, el nombre del archivo sin su extensión, y enabled es por defecto, true)

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +const debug = true;
Esto debería ser movido a `client.dev` en nuestros `KlasaClientOptions`.

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +		if (usuarios.length === 0 || !canal) return false;
Deberías revisar si el canal existe, antes que la petición a la base de datos.

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +		let channels = '';
```js
const channels = usuarios.map(usuario => usuario.nombreCuentaTwitch).join(',');
```

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +		console.log(channels);
¿Qué hace esto aquí?

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +		const res = await result.json();
El nombre de esta constante debería ser `body` para evitar confusiones con `Response`.

```js
const body = await fetch(url).then(result => result.json());
```

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +		for (let i = 0; i < res.streams.length; i++) {
Usa `for-of`, será mucho más eficiente y fácil de leer.

2018-07-31 11:24 UTC, kyranet commented on src/tasks/twitch.js
> +				const createdAt = await r.table('streams').get(res.streams[i]._id)('createdAt').default(-1);
Para todo esto, deberías hacer:

```js
for (const stream of res.streams) {
	let entry = await r.table('streams').get(stream.id);
	let nuevo = false;
	if (!entry) {
		nuevo = true;
		entry = { id: stream.id, createdAt: stream.created_at };
		await r.table('streams').get(stream.id).insert(entry);
	}

	if (nuevo || entry.createdAt !== stream.created_at) {
		if (!nuevo) await r.table('streams').get(stream.id).update({ createdAt: stream.created_at });
		const imagen = await guild.members.fetch(entry.id)
			.then(member => member.user.displayAvatarURL())
			.catch(() => undefined);
		await canal.send(new MessageEmbed()
			.setAuthor(stream.channel.display_name, imagen)
			.setThumbnail(stream.channel.logo)
			.setImage(stream.preview.large)
			.addField('Juego:', stream.game, true)
			.addField('Espectadores:', stream.viewers, true)
			.setColor(8478656));
	}
}
```

2018-08-02 14:43 UTC, kyranet requested changes

2018-08-02 14:43 UTC, kyranet commented on src/commands/Utiles/twitch.js
> +			usuarios.push(await msg.guild.members.get(entrada.id)
`msg.guild.members.get` -> `msg.guild.members.fetch`.

2018-08-02 14:43 UTC, kyranet commented on src/tasks/twitch.js
> +const url = new URL('https://api.twitch.tv/kraken/streams/');
Mueve esto adentro del run.

2018-08-02 14:43 UTC, kyranet commented on src/tasks/twitch.js
> +			let imagen;
```js
const streamerProfile = streamers.find(streamer => streamer.nombreCuentaTwitch === stream.channel.display_name);
const imagen = streamerProfile ? await guild.members.fetch(streamerProfile.id)
	.then(member => member.user.displayAvatarURL())
	.catch(() => undefined) : undefined;
```

2018-08-02 14:43 UTC, kyranet commented on src/tasks/twitch.js
> +		if (usuarios.length === 0) return false;
```js
if (!usuarios.length) return false;
```

2018-08-02 14:43 UTC, kyranet commented on src/tasks/twitch.js
> +		if (!canal) throw `No existe el canal, por favor reconfigurelo`;
Esto es un Task, los mensajes no son enviados a Discord, debes hacer `return false;`

2018-08-02 14:43 UTC, kyranet commented on src/bwd/guilds.schema.json
> +		"streamer": {
Esta clave no está siendo usada.

2018-08-02 14:43 UTC, kyranet commented on src/bwd/guilds.schema.json
> +		"usuario": {
Esta clave no está siendo usada.

2018-08-02 14:43 UTC, kyranet commented on src/bwd/guilds.schema.json
> +		"general": {
Esta clave no está siendo usada.

2018-08-02 14:43 UTC, kyranet commented on src/bwd/guilds.schema.json
> +		"cuestionario": {
Esta clave no está siendo usada.

2018-08-02 15:04 UTC, StartForKillerMC commented on src/bwd/guilds.schema.json
> +		"cuestionario": {
ah, es de otro proyecto xd

2018-08-03 08:17 UTC, kyranet approved these changes

2018-08-03 08:17 UTC, merged