Tripulacion
SeaOfThievesES/Tabernera pull request #20
Opened 2019-01-12 18:10 UTC by GGijon

Consolidados comandos de tripulaciones en el comando tripulacion y sus subcomandos

Agregadas opciones para ver una lista de tripulaciones, visualizacion y edicion de tripulaciones, opcion de abandonar para tripulantes y comandos de moderacion y borrado para el administrador

2019-01-12 19:12 UTC, kyranet requested changes
Muchísimos de los fallos son fácilmente arreglables utilizando el comando `eslint --fix src`.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			extendedHelp: ['',
```suggestion
			extendedHelp: [
				'',
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, "nombre de tripulación", "string", 1]);
Sólo una sugerencia... el constructor `Possible` es semi-privado en Klasa, lo que quieres usar es [`Command#customizeResponse`](https://klasa.js.org/#/docs/klasa/master/class/Command?scrollTo=customizeResponse)

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +	async listar(msg, []) {
```suggestion
	async listar(msg) {
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const crews = this.client.gateways.crews;
Si no recuerdo mal, las normas de ESLint de Klasa prefiere esto:
```suggestion
		const { crews } = this.client.gateways;
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const crews = this.client.gateways.crews;
Aunque lo cambiaré posteriormente ya que en un cambio futuro, `gateways` pasará a ser un mapa. Ya actualizaré Tabernera para ello cuando esté disponible.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		await crews.sync();
Esto no es necesario, todas las entradas están guardadas en la caché desde el inicio del bot.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			.setColor(0x2b9d98)
Usa los números hexadecimales en mayúsculas:
```suggestion
			.setColor(0x2B9D98)
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		sortedList.forEach(crew => embed.addField(crew.id, this.generateCrewShort(crew)));
```suggestion
		for (const crew of sortedList) embed.addField(crew.id, this.generateCrewShort(crew));
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const funnyNames = [
Si esto nunca cambia, deberías moverlo a un archivo de constantes.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		if (numCompanions == 1) {
```javascript
const funnyNameAdjective = funnyNames[adjectiveIndex][2];
const funnyNameCaptain = funnyNames[captainIndex][0];

if (numCompanions === 1)
	return `del ${funnyNameAdjective} ${funnyNameCaptain} <@${crew.owner}>`;

if (numCompanions === 2)
	return `del ${funnyNameAdjective} ${funnyNameCaptain} <@${crew.owner}> y otro ${funnyNames[companionsIndex][0]}`;

return `del ${funnyNameAdjective} ${funnyNameCaptain} <@${crew.owner}> y ${numCompanions - 1} ${funnyNames[companionsIndex][1]} más`;

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			crewLogo = "https://i.imgur.com/INxHGkP.png";
Deberían ser constantes.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		;
El punto y coma está solito, en unos meses volverá con esta reacción.

![](https://media.giphy.com/media/fR4xLFaHS6hAfLDGYa/giphy.gif)

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const embed = new MessageEmbed()
Simplemente haz el `return` aquí en vez de crear una constante.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const message = await msg.sendMessage(`¡Ojo al parche, ${member}! ¡${msg.author} quiere que te unas a su tripulación, <@&${userCrew.role}>! ¿Aceptas?`);
Si algo, prefiero mostrar el nombre del crew en vez de mencionar al rol entero.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const message = await msg.sendMessage(`¡Ojo al parche, ${member}! ¡${msg.author} quiere que te unas a su tripulación, <@&${userCrew.role}>! ¿Aceptas?`);
Y lo mismo para las otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reactionAccept = emojiAccept ? emojiAccept : '👍';
```suggestion
		const reactionAccept = emojiAccept || '👍';
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reactionReject = emojiReject ? emojiReject : '👎';
```suggestion
		const reactionReject = emojiReject || '👎';
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reactionReject = emojiReject ? emojiReject : '👎';
Aunque no creo que esto sea necesario, ya que nunca va a ser `null` en SettingsGateway, sino como mínimo, las reacciones por defecto del esquema de crews.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			{ max: 1, time: (invitationExpirationSeconds ? invitationExpirationSeconds : 300) * 1000 });
```suggestion
			{ max: 1, time: (invitationExpirationSeconds || 300) * 1000 });
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			{ max: 1, time: (invitationExpirationSeconds ? invitationExpirationSeconds : 300) * 1000 });
Y lo mismo que el comentario de arriba.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			{ max: 1, time: (invitationExpirationSeconds ? invitationExpirationSeconds : 300) * 1000 });
Aunque casi preferiría usar tasks, haremos eso después de esto.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		message.delete();
Maneja cualquier error que pueda tirar esto, si el bot no tiene permisos o Discord no se siente muy bien, esto tirará un error de promesa no manejada, el cual induce a un memory leak en Node.js.

![](https://media.giphy.com/media/AiEr9b7sX5VKIoIvQL/giphy.gif)

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		await crews.sync();
Lo mismo para todas las ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			if (joinedCrew.role === userCrew.role) return; // Don't show any message if the crew the target has already joined is ours
Esto debería mandar un mensaje diciendo que ya está unido, en vez de no decir nada (lo cual da mala señal).

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const { channelKickedVoice } = msg.guild.configs.crews;
Esta constante debería ser movido hasta casi al final, cuando se usa la variable, para evitar crear variables que no se usarán en más de la mitad de las ramas del flujo de código.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			await crew.update('pendingCrewLogo', text);
```suggestion
				await crew.update('pendingCrewLogo', text);
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			await crew.update('pendingCrewLogo', text);
Lo mismo para las otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			await crew.update('pendingCrewLogo', text);
Y para los `break;`

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +
```suggestion
```
no son necesarios los espacios blancos, ya que hay sangría en la anterior línea

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reportChannel = channelReportAdmin ? msg.guild.channels.find(channel => channel.id === channelReportAdmin) : undefined;
```suggestion
		const reportChannel = channelReportAdmin ? msg.guild.channels.find(channel => channel.id === channelReportAdmin) : null;
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		await crew.update('role', role);
```suggestion
		await crew.update(
			['role', 'channelText', 'channelVoice', 'owner', 'members'],
			[role, textChannel, voiceChannel, member, member]
		);
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		await crew.update('role', role);
Añade un `TODO` también ya que cuando actualicemos Tabernera a la última versión de Klasa, tendremos que usar array de tuples:

```javascript

await crew.update([
	['role', role],
	['channelText', textChannel],
	['channelVoice', voiceChannel],
	['owner', member],
	['members', member]
]);
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reportChannel = channelReportAdmin ? msg.guild.channels.find(channel => channel.id === channelReportAdmin) : undefined;
```suggestion
		const reportChannel = channelReportAdmin ? msg.guild.channels.find(channel => channel.id === channelReportAdmin) : null;
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			pendingCrews.forEach(crew => {
Usa `for...of` en vez de `forEach`

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			pendingCrews.forEach(crew => {
Lo mismo para todas otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				pending = pending.join(" + ");
En vez de cambiar el tipo de la variable `pending`, haz el join en addField

```suggestion
				embed.addField(crew.id, pending.join(' + '));
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				embed.addField(crew.id, pending)
¿Dónde está el punto y coma? Lo mismo para todas otras ocurrencias.

![](https://media.giphy.com/media/hEc4k5pN17GZq/giphy.gif)

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				msg.sendMessage(`Hablemos en privado, ${msg.author}.`);
`msg.sendMessage` devuelve una promesa, maneja cualquier error que pueda tirar.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				msg.sendMessage(`Hablemos en privado, ${msg.author}.`);
Lo mismo para todas otras ocurrencias, o utiliza `await`, así cualquier error tirado será captado por Klasa.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reactionAccept = emojiAccept ? emojiAccept : '👍';
```suggestion
		const reactionAccept = emojiAccept || '👍';
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const reactionReject = emojiReject ? emojiReject : '👎';
```suggestion
		const reactionReject = emojiReject || '👎';
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		if(crew.pendingCrewLogo) {
```suggestion
		if (crew.pendingCrewLogo) {
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +			.then(async (reacts) => {
No hagas esto, usa `const reacts = await message.awaitReactions(...);`

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		if(crew.pendingCrewLogo) {
Lo mismo para todas otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				}
El formato recomendado (y pedido por la configuración de ESLint) es la siguiente:

```javascript
if (condition) {
	// body
} else if (otherCondition) {
	// other body
} else {
	// last body
}
```

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				}
Lo mismo para todas otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, "nombre de tripulación", "string", 1]);
Ah, y utilizamos `'`, no `"`. Lo mismo para todas otras ocurrencias.

2019-01-12 19:12 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, "nombre de tripulación", "string", 1]);
También me gustaría no tener que usar esto ya que en un futuro nos gustaría tener soporte multilenguaje en Tabernera, y esto lo dificulta mucho.

2019-01-13 02:20 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, "nombre de tripulación", "string", 1]);
No tengo muy claro que el customizeResponse me sirva aqui. Los subcomandos pueden necesitar de cero a dos argumentos.
El primer argumento en unas ocasiones necesita ser un usuario (pirata, en reclutar, expulsar y crear), en otras un string (nombre de tripulacion, en moderar y borrar; o una opcion entre <logo|historia|imagen> en establecer) y en otras se ignora (listar, abandonar y opcionalmente moderar).

2019-01-13 02:23 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +		sortedList.forEach(crew => embed.addField(crew.id, this.generateCrewShort(crew)));
Hay alguna razon por la que la forma procedural sea mejor que la funcional?

2019-01-13 03:09 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +		const { channelKickedVoice } = msg.guild.configs.crews;
Otros comandos utilizan destructuring para extraer varios campos, unos utilizados casi de inmediato y otros solamente en ramas que a menudo no se ejecutan. Entiendo que en esos casos es mejor hacer un solo destructuring que multiples.

Si se acepta esa premisa, entiendo que la consistencia entre comandos (es decir, extraer los campos cerca del comienzo del codigo de todos los comandos) es menos confusa que el que cada comando haga la extraccion cuando le de la gana.

Como analogia, hacemos los requires al principio del archivo, no salteados por el codigo.

2019-01-13 03:44 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +		const funnyNames = [
He movido todas las constantes (titulos de embed, colores, imagenes y estos nombres) al comienzo del archivo.
Cuando puedas me dices donde colocar el archivo de constantes y lo llevo alli.

2019-01-20 18:18 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		sortedList.forEach(crew => embed.addField(crew.id, this.generateCrewShort(crew)));
1. Consistencia con el resto de código y bucles.
1. Más eficiente.
1. No crea stack traces.

2019-01-20 18:18 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const funnyNames = [
`/src/lib/util/constants.js`

2019-01-20 18:19 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const { channelKickedVoice } = msg.guild.configs.crews;
Deberían estar destructurados en demanda.

2019-01-20 18:41 UTC, kyranet requested changes

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				'',
Esta línea es innecesaria
```suggestion
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					if (!arg) arg = '';
Esta línea es innecesaria
```suggestion
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, 'nombre de tripulación', 'string', 1]);
Si un string vacío devuelve undefined, esto nunca será llamado, por lo tanto, puedes reducir toda esta rama a
```js
if (type === 'moderar') {
	return arg || undefined;
}
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					if (!arg) arg = '';
Estoy muy seguro que puedes reducir lo siguiente a
```js
arg = (arg || '').toLowerCase();
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +					const customPossible = new Possible([undefined, 'nombre de tripulación', 'string', 1]);
Y también, no me gusta abusar de los `Array#include()` ya que creas un array cada vez que llamas al método, es también más difícil de leer, propongo otras soluciones:

1. RegExp (`/(detalles|borrar)/.test(arg)`)
1. OR (`arg === 'detalles' || arg === 'borrar'`)
1. Constantes (`DETALLES_O_BORRAR.includes(arg)`)

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		switch (option) {
```javascript
const ESTABLECER_CLAVES = {
	logo: 'pendingCrewLogo',
	historia: 'pendingCrewDescription',
	imagen: 'pendingCrewImage'
};

// ...

if (option in ESTABLECER_CLAVES) await crew.update(ESTABLECER_CLAVES[option], text);
else throw '¡Diantres! ¡No entiendo la opción que has elegido!';
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const textChannel = await msg.guild.channels.create(crewName, {
Concurrencia sería lo preferido:
```javascript
const [textChannel, voiceChannel] = await Promise.all([
	/* create text channel */,
	/* create voice channel */
]);
```

2019-01-20 18:41 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		promises.push(moderationOption('logo', 'pendingCrewLogo', 'crewLogo'));
Preferiría no hacer los 3 concurrentes, ya que mandarías 3 mensajes a la vez con dos reacciones cada uno.

2019-01-20 19:42 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +				'',
No estoy de acuerdo, el mensaje de +ayuda tripulacion es mas legible asi

2019-01-20 20:10 UTC, GGijon commented on src/commands/Tripulacion/tripulacion.js
> +		promises.push(moderationOption('logo', 'pendingCrewLogo', 'crewLogo'));
Creo que es mejor asi, permite al usuario aceptar/rechazar algunas opciones inmediatamente y pensarse otras. De lo contrario necesitariamos una reaccion mas para "Pasar, me lo pienso mas adelante", o hacer que haya que pasarle al comando moderar cual de las opciones quieres revisar individualmente, lo que es menos usable.

2019-01-20 21:11 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +				'',
Entonces es un problema con el comando ayuda.

2019-01-20 21:27 UTC, kyranet requested changes

2019-01-20 21:27 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +const CrewsConstants = require('../../lib/util/CrewsConstants.js');
Si no es una clase, debería estar en pascalCase.
```suggestion
const crewsConstants = require('../../lib/util/CrewsConstants.js');
```

2019-01-20 21:27 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +const CrewsConstants = require('../../lib/util/CrewsConstants.js');
Y renombra todas las ocurrencias.

2019-01-20 21:27 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const dbKeys = {
Esto es una constante.

2019-01-20 21:27 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const { permission } = await this.client.permissionLevels.run(msg, 6);
```suggestion
		const permission = await msg.hasAtLeastPermissionLevel(6);
```

2019-01-20 21:27 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		const { permission } = await this.client.permissionLevels.run(msg, 6);
Lo mismo para las otras ocurrencias.

2019-01-20 21:27 UTC, kyranet commented on src/lib/util/CrewsConstants.js
> +const CrewsConstants = {
```suggestion
module.exports = {
```

2019-01-20 21:27 UTC, kyranet commented on src/lib/util/CrewsConstants.js
> +const CrewsConstants = {
Y quitas el `module.exports` de la última línea.

2019-01-20 21:35 UTC, kyranet commented on src/commands/Tripulacion/tripulacion.js
> +		promises.push(moderationOption('logo', 'pendingCrewLogo', 'crewLogo'));
Por decisión del equipo, debería preguntar en secuencia. Las tres preguntas a la vez sería demasiado agresivo, sin mencionar del tiempo de reacción compartido (el usuario tiene menos tiempo para decidir), lo cual hace que esto sea contraproducente. Es mejor coleccionar las tres respuestas y mandar un único mensaje. Mandar 3 mensajes cortos es un mal diseño.

2019-01-21 13:07 UTC, merged